"""Vendored Jost (OFL-1.1) and the type ramp."""

from parch.fonts.catalog import FontCatalog, TypeFamily, TypeWeight, font_dir, jost_catalog
from parch.fonts.ramp import (
    BRIDGE_BACKLOG,
    JOST_SCALE,
    MIGRATED_SURFACES,
    TYPE_STEPS,
    EffectiveRamp,
    FaceBridge,
    JostRamp,
    MigratedSurface,
    ScaleCut,
    TypeEmphasis,
    TypeFace,
    TypeInk,
    TypeOverlay,
    TypePatch,
    TypeRamp,
    TypeStep,
    apply_overlay,
    bind_ramp,
    compose_overlays,
    scale_ink,
)

__all__ = [
    "BRIDGE_BACKLOG",
    "EffectiveRamp",
    "FaceBridge",
    "FontCatalog",
    "JOST_SCALE",
    "JostRamp",
    "MIGRATED_SURFACES",
    "MigratedSurface",
    "ScaleCut",
    "TYPE_STEPS",
    "TypeEmphasis",
    "TypeFace",
    "TypeFamily",
    "TypeInk",
    "TypeOverlay",
    "TypePatch",
    "TypeRamp",
    "TypeStep",
    "TypeWeight",
    "apply_overlay",
    "bind_ramp",
    "compose_overlays",
    "font_dir",
    "jost_catalog",
    "scale_ink",
]
