"""Vendored Jost (OFL-1.1) and the type ramp."""

from parch.fonts.catalog import FontCatalog, TypeFamily, TypeWeight, font_dir, jost_catalog
from parch.fonts.ramp import (
    DISPLAY_SIZE,
    Em,
    JOST_RATIOS,
    JOST_SCALE,
    OVERLAY_SCHEMA_VERSION,
    PROOF_PROFILE,
    ROOT_BODY,
    TYPE_STEPS,
    EffectiveRamp,
    ProofProfile,
    Pt,
    ScaleCut,
    TypeEmphasis,
    TypeInk,
    TypeOverlay,
    TypePatch,
    TypeRamp,
    TypeRef,
    TypeStep,
    apply_overlay,
    bind_ramp,
    compose_overlays,
    pt_from_em,
    require_overlay,
    validate_overlay,
)

__all__ = [
    "DISPLAY_SIZE",
    "Em",
    "JOST_RATIOS",
    "JOST_SCALE",
    "OVERLAY_SCHEMA_VERSION",
    "PROOF_PROFILE",
    "ROOT_BODY",
    "TYPE_STEPS",
    "EffectiveRamp",
    "FontCatalog",
    "ProofProfile",
    "Pt",
    "ScaleCut",
    "TypeEmphasis",
    "TypeFamily",
    "TypeInk",
    "TypeOverlay",
    "TypePatch",
    "TypeRamp",
    "TypeRef",
    "TypeStep",
    "TypeWeight",
    "apply_overlay",
    "bind_ramp",
    "compose_overlays",
    "font_dir",
    "jost_catalog",
    "pt_from_em",
    "require_overlay",
    "validate_overlay",
]
