"""Vendored Jost (OFL-1.1) and the type ramp."""

from parch.fonts.catalog import FontCatalog, TypeFamily, TypeWeight, font_dir, jost_catalog
from parch.fonts.ramp import (
    OVERLAY_SCHEMA_VERSION,
    OVERLAY_SIZE_RANGE,
    BadWeight,
    EffectiveRamp,
    JostRamp,
    NonpositiveSize,
    OverlayOk,
    SizeOutOfRange,
    TypeInk,
    TypeOverlay,
    TypePatch,
    TypeRamp,
    TypeRole,
    TypeStep,
    UnknownStep,
    VersionMismatch,
    apply_overlay,
    bind_ramp,
    compose_overlays,
    jost_defaults,
    require_overlay,
    validate_overlay,
)

__all__ = [
    "OVERLAY_SCHEMA_VERSION",
    "OVERLAY_SIZE_RANGE",
    "BadWeight",
    "EffectiveRamp",
    "FontCatalog",
    "JostRamp",
    "NonpositiveSize",
    "OverlayOk",
    "SizeOutOfRange",
    "TypeFamily",
    "TypeInk",
    "TypeOverlay",
    "TypePatch",
    "TypeRamp",
    "TypeRole",
    "TypeStep",
    "TypeWeight",
    "UnknownStep",
    "VersionMismatch",
    "apply_overlay",
    "bind_ramp",
    "compose_overlays",
    "font_dir",
    "jost_catalog",
    "jost_defaults",
    "require_overlay",
    "validate_overlay",
]
